/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.shopping.app.admin.orders;

import com.mycompany.shopping.app.admin.dashboard.AdminDashboard;
import com.mycompany.shopping.app.admin.dashboard.SuperAdminDashboard;
import com.mycompany.shopping.app.dbConnection.SqlConnection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author THUSH
 */
public class ManageOrders extends javax.swing.JFrame {

    /**
     * Creates new form ManageOrders
     */
    String user_type = null;
    public ManageOrders(String user) {
        initComponents();
        SelectOrders();
        user_type = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        header = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        ProductListScrollPane1 = new javax.swing.JScrollPane();
        ProductListScrollPane2 = new javax.swing.JScrollPane();
        ProductListTable = new javax.swing.JTable();
        OrdersScrollPane1 = new javax.swing.JScrollPane();
        OrdersScrollPane2 = new javax.swing.JScrollPane();
        OrdersTable = new javax.swing.JTable();
        ProductList = new javax.swing.JLabel();
        Orders = new javax.swing.JLabel();
        StateComboBox1 = new javax.swing.JComboBox<>();
        SearchBtn = new javax.swing.JButton();
        FirstNameTextField = new javax.swing.JTextField();
        FirstName = new javax.swing.JLabel();
        LastNameTextField = new javax.swing.JTextField();
        LastName = new javax.swing.JLabel();
        PhoneNoTextField = new javax.swing.JTextField();
        PhoneNo = new javax.swing.JLabel();
        AddressLine1TextField = new javax.swing.JTextField();
        AddressLine1 = new javax.swing.JLabel();
        PostelCodeTextField = new javax.swing.JTextField();
        PostelCode = new javax.swing.JLabel();
        Country = new javax.swing.JLabel();
        CountryTextField = new javax.swing.JTextField();
        StateOrDivisionTextField = new javax.swing.JTextField();
        AddressLine2TextField = new javax.swing.JTextField();
        StateOrDivision = new javax.swing.JLabel();
        AddressLine2 = new javax.swing.JLabel();
        EmailTextField = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        HomeBtn = new javax.swing.JButton();
        DeleteOrderBtn = new javax.swing.JButton();
        SetStateBtn = new javax.swing.JButton();
        LastName1 = new javax.swing.JLabel();
        StateComboBox = new javax.swing.JComboBox<>();
        footer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1400, 750));
        setMinimumSize(new java.awt.Dimension(1400, 750));
        setPreferredSize(new java.awt.Dimension(1400, 750));

        header.setBackground(new java.awt.Color(255, 204, 51));
        header.setMaximumSize(new java.awt.Dimension(1000, 750));

        jPanel2.setBackground(new java.awt.Color(255, 204, 0));
        jPanel2.setMaximumSize(new java.awt.Dimension(1000, 32767));
        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 143));

        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\edu\\Edu IT\\edu projects\\project6\\Shopping-app\\shopping-desktop-app\\asserts\\images\\Textile-shop-header4.jpg")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 947, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1069, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        body.setMaximumSize(new java.awt.Dimension(1000, 32767));
        body.setPreferredSize(new java.awt.Dimension(1000, 514));

        ProductListScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        ProductListScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        ProductListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Main catagory", "Sub category", "Small Quantity", "Small Price ( Rs. )", "Medium Quantity", "Medium Price ( Rs. )", "Large Quantity", "Large Price ( Rs. )"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ProductListTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductListTableMouseClicked(evt);
            }
        });
        ProductListScrollPane2.setViewportView(ProductListTable);
        if (ProductListTable.getColumnModel().getColumnCount() > 0) {
            ProductListTable.getColumnModel().getColumn(0).setMinWidth(35);
            ProductListTable.getColumnModel().getColumn(0).setPreferredWidth(35);
            ProductListTable.getColumnModel().getColumn(1).setMinWidth(35);
            ProductListTable.getColumnModel().getColumn(1).setPreferredWidth(35);
            ProductListTable.getColumnModel().getColumn(2).setMinWidth(35);
            ProductListTable.getColumnModel().getColumn(2).setPreferredWidth(35);
            ProductListTable.getColumnModel().getColumn(3).setMinWidth(35);
            ProductListTable.getColumnModel().getColumn(3).setPreferredWidth(35);
            ProductListTable.getColumnModel().getColumn(4).setMinWidth(35);
            ProductListTable.getColumnModel().getColumn(4).setPreferredWidth(35);
            ProductListTable.getColumnModel().getColumn(5).setMinWidth(35);
            ProductListTable.getColumnModel().getColumn(5).setPreferredWidth(35);
            ProductListTable.getColumnModel().getColumn(6).setMinWidth(35);
            ProductListTable.getColumnModel().getColumn(6).setPreferredWidth(35);
            ProductListTable.getColumnModel().getColumn(7).setMinWidth(35);
            ProductListTable.getColumnModel().getColumn(7).setPreferredWidth(35);
            ProductListTable.getColumnModel().getColumn(8).setMinWidth(35);
            ProductListTable.getColumnModel().getColumn(8).setPreferredWidth(35);
        }

        ProductListScrollPane1.setViewportView(ProductListScrollPane2);

        OrdersScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        OrdersScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        OrdersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Customer ID", "Date and Time", "State"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        OrdersTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrdersTableMouseClicked(evt);
            }
        });
        OrdersScrollPane2.setViewportView(OrdersTable);

        OrdersScrollPane1.setViewportView(OrdersScrollPane2);

        ProductList.setBackground(new java.awt.Color(255, 255, 255));
        ProductList.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ProductList.setText("Product List");

        Orders.setBackground(new java.awt.Color(255, 255, 255));
        Orders.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Orders.setText("Orders");

        StateComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        StateComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select State", "All", "Pending", "Received" }));
        StateComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StateComboBox1MouseClicked(evt);
            }
        });

        SearchBtn.setBackground(new java.awt.Color(255, 204, 51));
        SearchBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SearchBtn.setText("Search");
        SearchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SearchBtnMouseEntered(evt);
            }
        });
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });

        FirstName.setBackground(new java.awt.Color(255, 255, 255));
        FirstName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FirstName.setText("First Name");

        LastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameTextFieldActionPerformed(evt);
            }
        });

        LastName.setBackground(new java.awt.Color(255, 255, 255));
        LastName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LastName.setText("Last Name");

        PhoneNoTextField.setText("\n");
        PhoneNoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneNoTextFieldActionPerformed(evt);
            }
        });

        PhoneNo.setBackground(new java.awt.Color(255, 255, 255));
        PhoneNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PhoneNo.setText("Telephone");

        AddressLine1.setBackground(new java.awt.Color(255, 255, 255));
        AddressLine1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AddressLine1.setText("Address line 1");

        PostelCode.setBackground(new java.awt.Color(255, 255, 255));
        PostelCode.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PostelCode.setText("Postel Code");

        Country.setBackground(new java.awt.Color(255, 255, 255));
        Country.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Country.setText("Country");

        CountryTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CountryTextFieldActionPerformed(evt);
            }
        });

        StateOrDivision.setBackground(new java.awt.Color(255, 255, 255));
        StateOrDivision.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        StateOrDivision.setText("State/Division");

        AddressLine2.setBackground(new java.awt.Color(255, 255, 255));
        AddressLine2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AddressLine2.setText("Address line 2");

        Email.setBackground(new java.awt.Color(255, 255, 255));
        Email.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Email.setText("Email");

        HomeBtn.setBackground(new java.awt.Color(255, 204, 51));
        HomeBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        HomeBtn.setText("BACK");
        HomeBtn.setBorder(null);
        HomeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomeBtnMouseEntered(evt);
            }
        });
        HomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeBtnActionPerformed(evt);
            }
        });

        DeleteOrderBtn.setBackground(new java.awt.Color(255, 204, 51));
        DeleteOrderBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DeleteOrderBtn.setText("Delete Order");
        DeleteOrderBtn.setBorder(null);
        DeleteOrderBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteOrderBtnMouseClicked(evt);
            }
        });
        DeleteOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteOrderBtnActionPerformed(evt);
            }
        });

        SetStateBtn.setBackground(new java.awt.Color(255, 204, 51));
        SetStateBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SetStateBtn.setText("Set State");
        SetStateBtn.setBorder(null);
        SetStateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SetStateBtnMouseClicked(evt);
            }
        });
        SetStateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetStateBtnActionPerformed(evt);
            }
        });

        LastName1.setBackground(new java.awt.Color(255, 255, 255));
        LastName1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LastName1.setText("State");

        StateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select State", "Pending", "Accepted" }));
        StateComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StateComboBoxMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bodyLayout = new javax.swing.GroupLayout(body);
        body.setLayout(bodyLayout);
        bodyLayout.setHorizontalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyLayout.createSequentialGroup()
                        .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OrdersScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(bodyLayout.createSequentialGroup()
                                .addComponent(Orders, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(StateComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(SearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38)
                        .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bodyLayout.createSequentialGroup()
                                .addComponent(StateOrDivision)
                                .addGap(18, 18, 18)
                                .addComponent(StateOrDivisionTextField))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bodyLayout.createSequentialGroup()
                                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AddressLine1)
                                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(FirstNameTextField)
                                    .addComponent(EmailTextField)
                                    .addComponent(AddressLine1TextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bodyLayout.createSequentialGroup()
                                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PostelCode, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LastName1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(bodyLayout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(StateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(SetStateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(bodyLayout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(PostelCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bodyLayout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyLayout.createSequentialGroup()
                                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Country, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AddressLine2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PhoneNoTextField)
                            .addComponent(LastNameTextField)
                            .addComponent(AddressLine2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CountryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(ProductList, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bodyLayout.createSequentialGroup()
                        .addComponent(ProductListScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(DeleteOrderBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        bodyLayout.setVerticalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyLayout.createSequentialGroup()
                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(FirstName)
                            .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(LastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LastName)
                                .addComponent(FirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bodyLayout.createSequentialGroup()
                                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Email)
                                    .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(AddressLine1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AddressLine1)))
                            .addGroup(bodyLayout.createSequentialGroup()
                                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(PhoneNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PhoneNo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(AddressLine2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AddressLine2))))
                        .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bodyLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Country)
                                    .addComponent(CountryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(bodyLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(StateOrDivisionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(StateOrDivision))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PostelCode)
                            .addComponent(PostelCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(StateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SetStateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LastName1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(bodyLayout.createSequentialGroup()
                        .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Orders, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(StateComboBox1)
                                .addComponent(SearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addComponent(OrdersScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(ProductList, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyLayout.createSequentialGroup()
                        .addComponent(ProductListScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyLayout.createSequentialGroup()
                        .addComponent(DeleteOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(HomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101))))
        );

        footer.setBackground(new java.awt.Color(255, 204, 51));

        javax.swing.GroupLayout footerLayout = new javax.swing.GroupLayout(footer);
        footer.setLayout(footerLayout);
        footerLayout.setHorizontalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        footerLayout.setVerticalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Bodoni MT Black", 1, 18)); // NOI18N
        jLabel1.setText("Manage Orders");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(footer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(583, 583, 583))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, 1380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addComponent(body, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StateComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StateComboBoxMouseClicked
 
    }//GEN-LAST:event_StateComboBoxMouseClicked
    
    private void ProductListTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductListTableMouseClicked

    }//GEN-LAST:event_ProductListTableMouseClicked
    
    int customerID;
    private void OrdersTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrdersTableMouseClicked
        DefaultTableModel model = (DefaultTableModel)OrdersTable.getModel();
        int Myindex = OrdersTable.getSelectedRow();
        
        customerID = Integer.parseInt(model.getValueAt(Myindex, 1).toString());
        
        int c;
        try{
            SqlConnection sqlConnection = new SqlConnection();        
            add = sqlConnection.con.prepareStatement("SELECT item_id, main_cat, cat_name, s_qty, price_s, m_qty, price_m, l_qty, price_l FROM textile_shop.order WHERE order_customer_id ="+customerID);
            Rs = add.executeQuery();
            
            ResultSetMetaData Rsd = Rs.getMetaData();
            c = Rsd.getColumnCount();
            
            DefaultTableModel d = (DefaultTableModel)ProductListTable.getModel();
            d.setRowCount(0);
            
            while(Rs.next()){
                Vector v = new Vector();
                
                for(int i=1; i<=c; i++){
                    v.add(Rs.getInt("item_id"));
                    v.add(Rs.getString("main_cat"));
                    v.add(Rs.getString("cat_name"));
                    v.add(Rs.getInt("s_qty"));
                    v.add(Rs.getInt("price_s"));
                    v.add(Rs.getInt("m_qty"));
                    v.add(Rs.getInt("price_m"));
                    v.add(Rs.getInt("l_qty"));
                    v.add(Rs.getInt("price_l"));                   
                }
                d.addRow(v);
            }
            
            setTextFields(customerID);
        }catch(SQLException e){
            e.printStackTrace();
        }
               
    }//GEN-LAST:event_OrdersTableMouseClicked

    private void StateComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StateComboBox1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_StateComboBox1MouseClicked

    int OrderID;
    String OrderState;
    private void SetStateBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SetStateBtnMouseClicked
        DefaultTableModel model = (DefaultTableModel)OrdersTable.getModel();
        int Myindex = OrdersTable.getSelectedRow();
        
        OrderID = Integer.parseInt(model.getValueAt(Myindex, 0).toString());
        OrderState = model.getValueAt(Myindex, 3).toString();
        
        if(!(StateComboBox.getSelectedItem().equals(OrderState))){    
            try{
                SqlConnection sqlConnection = new SqlConnection();
                add = sqlConnection.con.prepareStatement("UPDATE textile_shop.order SET state=? WHERE id="+OrderID);
                add.setString(1,StateComboBox.getSelectedItem().toString());

                row = add.executeUpdate();
                JOptionPane.showMessageDialog(this,"State Successfully Updated");
                SelectOrders();
            }catch(SQLException e){
                e.printStackTrace();
            }
        }else{
            JOptionPane.showMessageDialog(this,"Same State");
        }


    }//GEN-LAST:event_SetStateBtnMouseClicked

    private void SetStateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetStateBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SetStateBtnActionPerformed

    int dialogResult, row;
    private void DeleteOrderBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteOrderBtnMouseClicked
        DefaultTableModel model = (DefaultTableModel)OrdersTable.getModel();
        int Myindex = OrdersTable.getSelectedRow();
        
        OrderID = Integer.parseInt(model.getValueAt(Myindex, 0).toString());
        dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to delete the Order?", "Warning",JOptionPane.YES_NO_OPTION);
        
        if(dialogResult == JOptionPane.YES_OPTION){
            try{
                SqlConnection sqlConnection = new SqlConnection();
                add = sqlConnection.con.prepareStatement("DELETE FROM textile_shop.order WHERE id =?"); 
                add.setInt(1, OrderID);
                
                FirstNameTextField.setText("");
                LastNameTextField.setText("");
                PhoneNoTextField.setText("");
                EmailTextField.setText("");
                AddressLine1TextField.setText("");
                AddressLine2TextField.setText("");
                StateOrDivisionTextField.setText("");
                CountryTextField.setText("");
                PostelCodeTextField.setText("");
                StateComboBox.setSelectedItem("State");
                
                row = add.executeUpdate();
                JOptionPane.showMessageDialog(this,"Order Successfully Deleted");
                SelectOrders();
            }catch(SQLException e){
                e.printStackTrace();
            }
        }
        
    }//GEN-LAST:event_DeleteOrderBtnMouseClicked

    private void DeleteOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteOrderBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteOrderBtnActionPerformed

    private void HomeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeBtnMouseClicked
        if(user_type.equals("SA")){
            new SuperAdminDashboard(user_type).setVisible(true);
        }else{
            new AdminDashboard(user_type).setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_HomeBtnMouseClicked

    private void HomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeBtnActionPerformed

    private void HomeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeBtnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeBtnMouseEntered

    private void SearchBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchBtnMouseClicked
        
        if(StateComboBox1.getSelectedItem().equals("Pending") || StateComboBox1.getSelectedItem().equals("Received")){
            int c;
            String s = StateComboBox1.getSelectedItem().toString();
            try{
                SqlConnection sqlConnection = new SqlConnection();
                add = sqlConnection.con.prepareStatement("SELECT id, order_customer_id, createdAt, state FROM textile_shop.order WHERE state=?");
                add.setString(1, s);
                Rs = add.executeQuery();

                ResultSetMetaData Rsd = Rs.getMetaData();
                c = Rsd.getColumnCount();

                DefaultTableModel d = (DefaultTableModel)OrdersTable.getModel();
                d.setRowCount(0);

                while(Rs.next()){
                    Vector v = new Vector();

                    for(int i=1; i<=c; i++){
                        v.add(Rs.getInt("id"));
                        v.add(Rs.getInt("order_customer_id"));
                        v.add(Rs.getString("createdAt"));
                        v.add(Rs.getString("state"));

                    }
                    d.addRow(v);
                }

            }catch(SQLException e){
                e.printStackTrace();
            }
        } else {
            SelectOrders();
        }
    }//GEN-LAST:event_SearchBtnMouseClicked

    private void SearchBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchBtnMouseEntered
        
    }//GEN-LAST:event_SearchBtnMouseEntered

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchBtnActionPerformed

    private void PhoneNoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneNoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneNoTextFieldActionPerformed

    private void CountryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CountryTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CountryTextFieldActionPerformed

    private void LastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameTextFieldActionPerformed

    public void setTextFields(int customerID){
        try{
            SqlConnection sqlConnection = new SqlConnection();
            add = sqlConnection.con.prepareStatement("SELECT first_name, last_name, phone_number, email, address_line_1, address_line_2, state, country, postel_code FROM textile_shop.order_customer WHERE signup_id ="+customerID);
            Rs = add.executeQuery();
            
            if(Rs.next()){
                FirstNameTextField.setText(Rs.getString("first_name"));
                LastNameTextField.setText(Rs.getString("last_name"));
                PhoneNoTextField.setText(Rs.getString("phone_number"));
                EmailTextField.setText(Rs.getString("email"));
                AddressLine1TextField.setText(Rs.getString("address_line_1"));
                AddressLine2TextField.setText(Rs.getString("address_line_2"));
                StateOrDivisionTextField.setText(Rs.getString("state"));
                CountryTextField.setText(Rs.getString("country"));
                PostelCodeTextField.setText(Rs.getString("postel_code"));
            }
            
            DefaultTableModel model = (DefaultTableModel)OrdersTable.getModel();
            int Myindex = OrdersTable.getSelectedRow();
            StateComboBox.setSelectedItem(model.getValueAt(Myindex, 3).toString());
                   
        }catch(SQLException e){
            e.printStackTrace();
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    
    Statement St = null;
    ResultSet Rs = null;
    PreparedStatement add = null;
    
    public void SelectOrders(){
        int c;
        try{

            SqlConnection sqlConnection =  new SqlConnection();
            add = sqlConnection.con.prepareStatement("SELECT id, order_customer_id, createdAt, state FROM textile_shop.order");
            Rs = add.executeQuery();
            
            ResultSetMetaData Rsd = Rs.getMetaData();
            c = Rsd.getColumnCount();
            
            DefaultTableModel d = (DefaultTableModel)OrdersTable.getModel();
            d.setRowCount(0);
            
            while(Rs.next()){
                Vector v = new Vector();
                
                for(int i=1; i<=c; i++){
                    v.add(Rs.getInt("id"));
                    v.add(Rs.getInt("order_customer_id"));
                    v.add(Rs.getString("createdAt"));
                    v.add(Rs.getString("state"));
                    
                }
                d.addRow(v);
            }
            
        }catch(SQLException e){
            e.printStackTrace();
        }
    }
        
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageOrders("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressLine1;
    private javax.swing.JTextField AddressLine1TextField;
    private javax.swing.JLabel AddressLine2;
    private javax.swing.JTextField AddressLine2TextField;
    private javax.swing.JLabel Country;
    private javax.swing.JTextField CountryTextField;
    private javax.swing.JButton DeleteOrderBtn;
    private javax.swing.JLabel Email;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JLabel FirstName;
    private javax.swing.JTextField FirstNameTextField;
    private javax.swing.JButton HomeBtn;
    private javax.swing.JLabel LastName;
    private javax.swing.JLabel LastName1;
    private javax.swing.JTextField LastNameTextField;
    private javax.swing.JLabel Orders;
    private javax.swing.JScrollPane OrdersScrollPane1;
    private javax.swing.JScrollPane OrdersScrollPane2;
    private javax.swing.JTable OrdersTable;
    private javax.swing.JLabel PhoneNo;
    private javax.swing.JTextField PhoneNoTextField;
    private javax.swing.JLabel PostelCode;
    private javax.swing.JTextField PostelCodeTextField;
    private javax.swing.JLabel ProductList;
    private javax.swing.JScrollPane ProductListScrollPane1;
    private javax.swing.JScrollPane ProductListScrollPane2;
    private javax.swing.JTable ProductListTable;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JButton SetStateBtn;
    private javax.swing.JComboBox<String> StateComboBox;
    private javax.swing.JComboBox<String> StateComboBox1;
    private javax.swing.JLabel StateOrDivision;
    private javax.swing.JTextField StateOrDivisionTextField;
    private javax.swing.JPanel body;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel footer;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
