/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.shopping.app.admin.manageProduct;

import com.mycompany.shopping.app.admin.dashboard.AdminDashboard;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gayan Malinda
 */
public class ManageProduct extends javax.swing.JFrame {

    /**
     * Creates new form manageProduct
     */
    public ManageProduct() {
        initComponents();
        SelectProducts();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        ProductNameLabel = new javax.swing.JLabel();
        ProductNameTextfield = new javax.swing.JTextField();
        CategoryLabel = new javax.swing.JLabel();
        SmallSize = new javax.swing.JLabel();
        DescriptionLabel = new javax.swing.JLabel();
        AddBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        DescriptionTextArea = new javax.swing.JTextArea();
        DeleteBtn = new javax.swing.JButton();
        HomeBtn = new javax.swing.JButton();
        EditBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        QtyAndPriceLabel = new javax.swing.JLabel();
        SmallQty = new javax.swing.JTextField();
        SmallPrice = new javax.swing.JTextField();
        SRs = new javax.swing.JLabel();
        MainCategoryComboBox = new javax.swing.JComboBox<>();
        SubCategoryComboBox = new javax.swing.JComboBox<>();
        Img1Label = new javax.swing.JLabel();
        Img1Path = new javax.swing.JTextField();
        Img2Path = new javax.swing.JTextField();
        Img2Label = new javax.swing.JLabel();
        Img3Path = new javax.swing.JTextField();
        Img3Label = new javax.swing.JLabel();
        MediumSize = new javax.swing.JLabel();
        MediumQty = new javax.swing.JTextField();
        MRs = new javax.swing.JLabel();
        MediumPrice = new javax.swing.JTextField();
        LargeSize = new javax.swing.JLabel();
        LargeQty = new javax.swing.JTextField();
        LRs = new javax.swing.JLabel();
        LargePrice = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProductInfoTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 204, 51));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 204, 0));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField1.setText("Kingsmen Textiles");
        jTextField1.setBorder(null);
        jTextField1.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(255, 204, 0));
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(51, 51, 51));
        jTextField2.setText("Manage Products");
        jTextField2.setBorder(null);
        jTextField2.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(426, 426, 426)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ProductNameLabel.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        ProductNameLabel.setText("Product Name");
        ProductNameLabel.setMinimumSize(new java.awt.Dimension(49, 27));

        ProductNameTextfield.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ProductNameTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductNameTextfieldActionPerformed(evt);
            }
        });

        CategoryLabel.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        CategoryLabel.setText("Category");
        CategoryLabel.setMinimumSize(new java.awt.Dimension(49, 27));

        SmallSize.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        SmallSize.setText("S");
        SmallSize.setMinimumSize(new java.awt.Dimension(49, 27));

        DescriptionLabel.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        DescriptionLabel.setText("Description");
        DescriptionLabel.setMinimumSize(new java.awt.Dimension(49, 27));

        AddBtn.setBackground(new java.awt.Color(255, 153, 51));
        AddBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        AddBtn.setForeground(new java.awt.Color(102, 102, 102));
        AddBtn.setText("Add");
        AddBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddBtnMouseClicked(evt);
            }
        });
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 204, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        DescriptionTextArea.setColumns(1);
        DescriptionTextArea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DescriptionTextArea.setRows(5);
        DescriptionTextArea.setWrapStyleWord(true);
        jScrollPane2.setViewportView(DescriptionTextArea);

        DeleteBtn.setBackground(new java.awt.Color(255, 153, 51));
        DeleteBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        DeleteBtn.setForeground(new java.awt.Color(102, 102, 102));
        DeleteBtn.setText("Delete");
        DeleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteBtnMouseClicked(evt);
            }
        });
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        HomeBtn.setBackground(new java.awt.Color(255, 204, 51));
        HomeBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        HomeBtn.setForeground(new java.awt.Color(102, 102, 102));
        HomeBtn.setText("Home");
        HomeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeBtnMouseClicked(evt);
            }
        });
        HomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeBtnActionPerformed(evt);
            }
        });

        EditBtn.setBackground(new java.awt.Color(255, 153, 51));
        EditBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        EditBtn.setForeground(new java.awt.Color(102, 102, 102));
        EditBtn.setText("Edit");
        EditBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditBtnMouseClicked(evt);
            }
        });
        EditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBtnActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 204, 51));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        QtyAndPriceLabel.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        QtyAndPriceLabel.setText("Quantity and Price");
        QtyAndPriceLabel.setMinimumSize(new java.awt.Dimension(49, 27));

        SmallQty.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        SmallQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SmallQtyActionPerformed(evt);
            }
        });

        SmallPrice.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        SmallPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SmallPriceActionPerformed(evt);
            }
        });

        SRs.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        SRs.setText("Rs.");
        SRs.setMinimumSize(new java.awt.Dimension(49, 27));

        MainCategoryComboBox.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        MainCategoryComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Men", "Women" }));

        SubCategoryComboBox.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        SubCategoryComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        SubCategoryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubCategoryComboBoxActionPerformed(evt);
            }
        });

        Img1Label.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        Img1Label.setText("Image 1");
        Img1Label.setMinimumSize(new java.awt.Dimension(49, 27));

        Img1Path.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Img1Path.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Img1PathActionPerformed(evt);
            }
        });

        Img2Path.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Img2Path.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Img2PathActionPerformed(evt);
            }
        });

        Img2Label.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        Img2Label.setText("Image 2");
        Img2Label.setMinimumSize(new java.awt.Dimension(49, 27));

        Img3Path.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Img3Path.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Img3PathActionPerformed(evt);
            }
        });

        Img3Label.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        Img3Label.setText("Image 3");
        Img3Label.setMinimumSize(new java.awt.Dimension(49, 27));

        MediumSize.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        MediumSize.setText("M");
        MediumSize.setMinimumSize(new java.awt.Dimension(49, 27));

        MediumQty.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        MediumQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MediumQtyActionPerformed(evt);
            }
        });

        MRs.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        MRs.setText("Rs.");
        MRs.setMinimumSize(new java.awt.Dimension(49, 27));

        MediumPrice.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        MediumPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MediumPriceActionPerformed(evt);
            }
        });

        LargeSize.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        LargeSize.setText("L");
        LargeSize.setMinimumSize(new java.awt.Dimension(49, 27));

        LargeQty.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        LargeQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LargeQtyActionPerformed(evt);
            }
        });

        LRs.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        LRs.setText("Rs.");
        LRs.setMinimumSize(new java.awt.Dimension(49, 27));

        LargePrice.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        LargePrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LargePriceActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        ProductInfoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Main Category", "Sub Category", "Description", "Small Size Quantity", "Small Size Unit Price", "Medium Size Quantity", "Medium Size Unit Price", "Large Size Quantity", "Large Size Unit Price", "Image 1", "Image 2", "Image 3"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        ProductInfoTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductInfoTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ProductInfoTable);

        jScrollPane3.setViewportView(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Img3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Img3Path, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ProductNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ProductNameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CategoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(MainCategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SubCategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(DescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QtyAndPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(SmallSize, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(SmallQty, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(SRs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(SmallPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(MediumSize, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(MediumQty, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(MRs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(MediumPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(LargeSize, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(LargeQty, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(LRs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(LargePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Img1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(Img1Path, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Img2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(Img2Path, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(EditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(DeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(HomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(ProductNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ProductNameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(CategoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MainCategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SubCategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addComponent(DescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(QtyAndPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SmallQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SmallPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SmallSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SRs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MediumQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MediumPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MediumSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MRs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LargeQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LargePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LargeSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LRs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(Img1Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Img1Path, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(Img2Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Img2Path, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Img3Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Img3Path, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(HomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void ProductNameTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductNameTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductNameTextfieldActionPerformed

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddBtnActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void HomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeBtnActionPerformed

    private void EditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditBtnActionPerformed

    private void SmallQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SmallQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SmallQtyActionPerformed

    private void SmallPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SmallPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SmallPriceActionPerformed

    private void SubCategoryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubCategoryComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubCategoryComboBoxActionPerformed

    private void Img1PathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Img1PathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Img1PathActionPerformed

    private void Img2PathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Img2PathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Img2PathActionPerformed

    private void Img3PathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Img3PathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Img3PathActionPerformed

    private void MediumQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MediumQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MediumQtyActionPerformed

    private void MediumPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MediumPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MediumPriceActionPerformed

    private void LargeQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LargeQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LargeQtyActionPerformed

    private void LargePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LargePriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LargePriceActionPerformed
  
    Connection Con = null;
    Statement St = null;
    ResultSet Rs = null;
    PreparedStatement add = null;
    
    public void SelectProducts(){
        int c;
        try{
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/textile_shop","root","#19KKas99@%");
            add = Con.prepareStatement("select * from items");
            Rs = add.executeQuery();
            
            ResultSetMetaData Rsd = Rs.getMetaData();
            c = Rsd.getColumnCount();
            
            DefaultTableModel d = (DefaultTableModel)ProductInfoTable.getModel();
            d.setRowCount(0);
            
            while(Rs.next()){
                Vector v = new Vector();
                
                for(int i=1; i<=c; i++){
                    v.add(Rs.getInt("item_id"));
                    v.add(Rs.getString("name"));
                    v.add(Rs.getString("main_cat"));
                    v.add(Rs.getString("cat_name"));
                    v.add(Rs.getString("desc"));
                    v.add(Rs.getInt("qty_s"));
                    v.add(Rs.getInt("price_s"));
                    v.add(Rs.getInt("qty_m"));
                    v.add(Rs.getInt("price_m"));
                    v.add(Rs.getInt("qty_l"));
                    v.add(Rs.getInt("price_l"));
                    v.add(Rs.getString("img1"));
                    v.add(Rs.getString("img2"));
                    v.add(Rs.getString("img3"));
                }
                d.addRow(v);
            }
            
            Con.close();
        }catch(SQLException e){
            e.printStackTrace();
        }
    }
    
    int row;
    private void AddBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddBtnMouseClicked
        try{
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/textile_shop","root","#19KKas99@%");
            add = Con.prepareStatement("insert into items(main_cat, cat_name, name, qty_s, qty_m, qty_l, price_s, price_m, price_l, img1, img2, img3, `desc`) values(?,?,?,?,?,?,?,?,?,?,?,?,?)");
            
            add.setString(1,MainCategoryComboBox.getSelectedItem().toString());
            add.setString(2,SubCategoryComboBox.getSelectedItem().toString());
            add.setString(3, ProductNameTextfield.getText());
            add.setInt(4, Integer.valueOf(SmallQty.getText()));
            add.setInt(5, Integer.valueOf(MediumQty.getText()));
            add.setInt(6, Integer.valueOf(LargeQty.getText()));
            add.setDouble(7, Double.valueOf(SmallPrice.getText()));
            add.setDouble(8, Double.valueOf(MediumPrice.getText()));
            add.setDouble(9, Double.valueOf(LargePrice.getText()));
            add.setString(10, Img1Path.getText());
            add.setString(11, Img2Path.getText());
            add.setString(12, Img3Path.getText());
            add.setString(13, DescriptionTextArea.getText());
            
            row = add.executeUpdate();
            JOptionPane.showMessageDialog(this,"Product Successfully Added");
            Con.close();
            SelectProducts();
        }catch(SQLException e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_AddBtnMouseClicked

    int dialogResult;
    private void DeleteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteBtnMouseClicked
        DefaultTableModel model = (DefaultTableModel)ProductInfoTable.getModel();
        int Myindex = ProductInfoTable.getSelectedRow();
        
        ProductID = Integer.parseInt(model.getValueAt(Myindex, 0).toString());
        dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to delete the record?", "Warning",JOptionPane.YES_NO_OPTION);
        
        if(dialogResult == JOptionPane.YES_OPTION){
            try{
                Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/textile_shop","root","#19KKas99@%");
                add = Con.prepareStatement("delete from items where item_id =?"); 
                add.setInt(1, ProductID);
                
                ProductNameTextfield.setText("");
                MainCategoryComboBox.setSelectedItem("Men");
                SubCategoryComboBox.setSelectedItem("Item 1");
                DescriptionTextArea.setText("");
                SmallQty.setText("");
                SmallPrice.setText("");
                MediumQty.setText("");
                MediumPrice.setText("");
                LargeQty.setText("");
                LargePrice.setText("");
                Img1Path.setText("");
                Img2Path.setText("");
                Img3Path.setText("");
                
                row = add.executeUpdate();
                JOptionPane.showMessageDialog(this,"Product Successfully Deleted");
                Con.close();
            SelectProducts();
            }catch(SQLException e){
                e.printStackTrace();
            }
        }
        
    }//GEN-LAST:event_DeleteBtnMouseClicked

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void ProductInfoTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductInfoTableMouseClicked
        DefaultTableModel model = (DefaultTableModel)ProductInfoTable.getModel();
        int Myindex = ProductInfoTable.getSelectedRow();
        ProductNameTextfield.setText(model.getValueAt(Myindex, 1).toString());
        MainCategoryComboBox.setSelectedItem(model.getValueAt(Myindex, 2).toString());
        SubCategoryComboBox.setSelectedItem(model.getValueAt(Myindex, 3).toString());
        DescriptionTextArea.setText(model.getValueAt(Myindex, 4).toString());
        SmallQty.setText(model.getValueAt(Myindex, 5).toString());
        SmallPrice.setText(model.getValueAt(Myindex, 6).toString());
        MediumQty.setText(model.getValueAt(Myindex, 7).toString());
        MediumPrice.setText(model.getValueAt(Myindex, 8).toString());
        LargeQty.setText(model.getValueAt(Myindex, 9).toString());
        LargePrice.setText(model.getValueAt(Myindex, 10).toString());
        Img1Path.setText(model.getValueAt(Myindex, 11).toString());
        Img2Path.setText(model.getValueAt(Myindex, 12).toString());
        Img3Path.setText(model.getValueAt(Myindex, 13).toString());
    }//GEN-LAST:event_ProductInfoTableMouseClicked

    int ProductID;
    private void EditBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditBtnMouseClicked
        DefaultTableModel model = (DefaultTableModel)ProductInfoTable.getModel();
        int Myindex = ProductInfoTable.getSelectedRow();
        
        ProductID = Integer.parseInt(model.getValueAt(Myindex, 0).toString());
        try{
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/textile_shop","root","#19KKas99@%");
            add = Con.prepareStatement("update items set main_cat=?, cat_name=?, name=?, qty_s=?, qty_m=?, qty_l=?, price_s=?, price_m=?, price_l=?, img1=?, img2=?, img3=?, `desc`=? where item_id ="+ProductID);
            
            add.setString(1,MainCategoryComboBox.getSelectedItem().toString());
            add.setString(2,SubCategoryComboBox.getSelectedItem().toString());
            add.setString(3, ProductNameTextfield.getText());
            add.setInt(4, Integer.valueOf(SmallQty.getText()));
            add.setInt(5, Integer.valueOf(MediumQty.getText()));
            add.setInt(6, Integer.valueOf(LargeQty.getText()));
            add.setDouble(7, Double.valueOf(SmallPrice.getText()));
            add.setDouble(8, Double.valueOf(MediumPrice.getText()));
            add.setDouble(9, Double.valueOf(LargePrice.getText()));
            add.setString(10, Img1Path.getText());
            add.setString(11, Img2Path.getText());
            add.setString(12, Img3Path.getText());
            add.setString(13, DescriptionTextArea.getText());
            
            row = add.executeUpdate();
            JOptionPane.showMessageDialog(this,"Product Successfully Updated");
            Con.close();
            SelectProducts();
        }catch(SQLException e){
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_EditBtnMouseClicked

    private void HomeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeBtnMouseClicked
        new AdminDashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomeBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ManageProduct().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JLabel CategoryLabel;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JLabel DescriptionLabel;
    private javax.swing.JTextArea DescriptionTextArea;
    private javax.swing.JButton EditBtn;
    private javax.swing.JButton HomeBtn;
    private javax.swing.JLabel Img1Label;
    private javax.swing.JTextField Img1Path;
    private javax.swing.JLabel Img2Label;
    private javax.swing.JTextField Img2Path;
    private javax.swing.JLabel Img3Label;
    private javax.swing.JTextField Img3Path;
    private javax.swing.JLabel LRs;
    private javax.swing.JTextField LargePrice;
    private javax.swing.JTextField LargeQty;
    private javax.swing.JLabel LargeSize;
    private javax.swing.JLabel MRs;
    private javax.swing.JComboBox<String> MainCategoryComboBox;
    private javax.swing.JTextField MediumPrice;
    private javax.swing.JTextField MediumQty;
    private javax.swing.JLabel MediumSize;
    private javax.swing.JTable ProductInfoTable;
    private javax.swing.JLabel ProductNameLabel;
    private javax.swing.JTextField ProductNameTextfield;
    private javax.swing.JLabel QtyAndPriceLabel;
    private javax.swing.JLabel SRs;
    private javax.swing.JTextField SmallPrice;
    private javax.swing.JTextField SmallQty;
    private javax.swing.JLabel SmallSize;
    private javax.swing.JComboBox<String> SubCategoryComboBox;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
